import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/Link'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'
// import font from '../font/Montserrat-Medium.woff'
export default function Home () {
  return (
    <div className={styles.container}>
      <Header />
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        {/* <style type='text/css'>
          {`@font-face {
            font-family: 'Montserrat-Medium';
            font-display: swap;
            src:url(${font})
          }`}
        </style> */}
      </Head>

      <main>
        <Link href='/about'>ABOUT</Link>
        <br />
        <Image src={'/images/HDP-card.jpg'} height='400' width='400' />
        <br />
      </main>
    </div>
  )
}
